print("Starting simulation...")
print("")
print("I am standing in the kitchen.")
print("")
print("There's a stove to the North, a sink to the East, a table to the South, a fridge to the West, a light above me, and a french bulldog at my feet.")
print("")
print("What will I do?")
print("")
action = input("I will... ")
print("I", action)
